## Introduction to Tensorflow

In [2]:
#importin Tensorflow
import tensorflow as tf # type: ignore

print(tf.__version__)


2.15.0


In [3]:
#creating Tensor with constant

scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
#check number of dimentions in tensor
scalar.ndim

0

In [5]:
#create vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
#check number of dimentions in vector
vector.ndim

1

In [7]:
#create matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
#check number of dimentions
matrix.ndim

2

In [9]:
#creat specfic matrix
new_matrix=tf.constant([[10.,7.],
                        [7.,19.],
                        [1.,10.]],dtype=tf.float16)
new_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 19.],
       [ 1., 10.]], dtype=float16)>

In [10]:
#number of dimentions in new_matrix
new_matrix.ndim


2

In [11]:
#create tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9,],
                       [10,11,12]],
                      [[13,14,15,],
                       [16,17,18],]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [12]:
#number of dimentions in tensor
tensor.ndim

3

In [13]:
tensor1=tf.constant([[
    [[ 1,  2,  3],
    [ 4,  5,  6]],
    ],

   [
      [[ 1,  2,  3],
      [ 4,  5,  6]],
                      ],
                     [
      [[ 1,  2,  3],
      [ 4,  5,  6]],
                      ]
                     ])
tensor1

<tf.Tensor: shape=(3, 1, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]]]])>

In [14]:
#number of dimention of new tensor
tensor1.ndim

4



---
## Make tensors with **tf.variable**


tf.variable is tensor wich can be change but the tf.constant is a tensor wich cann't be change

In [15]:
#create tensor with tf.variable
changeable_tensor = tf.Variable([[10,6],[4,88]])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  6],
       [ 4, 88]])>

In [16]:
changeable_tensor[0].assign(7,)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 7,  7],
       [ 4, 88]])>

# create tensor from random

In [17]:
random_1= tf.random.Generator.from_seed(42)
random_1= random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

# shuffle the elements in tensor

In [18]:
shuffle_tensor = tf.Variable([[1,2,3],
                              [4,5,6],
                              [7,8,9]])
shuffle_tensor

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [19]:
# tf.random.set_seed(32)
tf.random.shuffle(shuffle_tensor,seed=32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])>

## Make tensor with Numpy

In [20]:
import numpy as np # type: ignore

array = np.arange(24)
tensor_numpy = tf.constant(array,shape=(2,3,4))


array,tensor_numpy

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])>)

## Get information from tensor

# Tensor Attributes :
* Shape ----- tf.shape
* Rank ----- tf.ndim
* Axis or dimension -----tensor [0], tensor [:  , 1]
* size -----tf.size(tensor)

In [21]:
import numpy as np # type: ignore

tf.ones(10)
tf.zeros([3,5],tf.int32)


rank_4 = tf.zeros([2,3,4,5])

rank_4


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank_4[1,0],tf.size(rank_4)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [23]:
rank_1 = tf.Variable([[[[1., 0., 0., 0., 0.],
                       [0., 2., 0., 0., 0.],
                        [0., 0., 3., 0., 0.],
                        [0., 0., 0.,4., 0.]],

                       [[0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0.]],

                       [[0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0.]]],


                      [[[0., 0., 0., 0., 0.],
                        [0., 0., 0., 0., 0.],
                          [0., 0., 0., 0., 0.],
                          [0., 0., 0., 0., 0.]],

                       [[0., 0., 0., 0., 0.],
                          [0., 0., 0., 0., 0.],
                          [0., 0., 0., 0., 0.],
                          [0., 0., 0., 0., 0.]],

                       [[0., 0., 0., 0., 0.],
                          [0., 0., 0., 0., 0.],
                          [0., 0., 0., 0., 0.],
                          [0., 0., 0., 0., 0.]]]])

In [24]:
#Get all attributes of our rank_4 tensor ✌️


print("DataType= ",rank_4.dtype)
print("Shape= ",rank_4.shape)

print("Rank = ",rank_4.ndim)
print("Elements of [0] shape = ",rank_4.shape[0])

print("Axis = ", rank_4[0, 0, 0].numpy())

print("size = ",tf.size(rank_4).numpy())

DataType=  <dtype: 'float32'>
Shape=  (2, 3, 4, 5)
Rank =  4
Elements of [0] shape =  2
Axis =  [0. 0. 0. 0. 0.]
size =  120


## Indexing Tensors : like python list

In [25]:
#get the first 2 elements for each block of array
print(rank_1.shape)

rank_1[:2, :2, :2, :2]

for i in range(4):
     print(rank_1[:1,:1,i,i])

(2, 3, 4, 5)
tf.Tensor([[1.]], shape=(1, 1), dtype=float32)
tf.Tensor([[2.]], shape=(1, 1), dtype=float32)
tf.Tensor([[3.]], shape=(1, 1), dtype=float32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


## ADD extra dimention for our tensor

In [34]:
tns1= tf.constant([[10,7],
                   [3,4]])
tns2 = tns1[..., tf.newaxis]
tns2

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [33]:
# the same value for tf.newaxis and there we select where we want the new dimention
tf.expand_dims(tns1,axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[7],
        [4]],

       [[2],
        [1]]])>

# manipulating tensors
**Basic operation**

In [36]:
# + , - , * , /
import time as time
import random as random

tns3=tf.constant([[10,7],
                  [3,4]])
print(tns3 + 10)
print(tns3 - 5)
print(tns3 * 2)
print(tns3 / 3)

tns4 = tf.multiply(tns3, random.randint(1, 100)) + random.randint(1, 100)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5  2]
 [-2 -1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 14]
 [ 6  8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3.33333333 2.33333333]
 [1.         1.33333333]], shape=(2, 2), dtype=float64)


## matrix multiplication
* most common operation in Tensors manipulation 

In [48]:
tns1 * tns3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [49]:
tf.matmul(tns1,tns3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [50]:
# matrix multiplication with @ :: python opariter
tns1 @ tns3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [63]:
# if the tensor are not combin we use reshalpe to make multplication avalible
multi_tns1 =tf.constant([[1,2],
                         [3,4],
                         [5,6]])
multi_tns2 =tf.constant([[7,8],
                         [9,10],
                         [11,12]])
multi_tns1 @ tf.reshape(multi_tns2,[2,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [79]:
# do it with transpose
# transpose make the line as colume and the colume as

multi_tns1 @ tf.transpose(multi_tns2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [80]:
tf.tensordot(multi_tns1,tf.transpose(multi_tns2), axes=1,)

# to make multiplication with tensor :
#    1- with python parametr @ 
#    2- with tf.transpose
#    2- with tf.matmul
# to make reshape :
#    1- reshape()
#    2- transpose
#    3- 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>