# changing datatype of a tensor

In [2]:
import tensorflow as tf

print(tf.__version__)


2.15.0


In [3]:
a = tf.constant([1,7]) #----> int32
b = tf.constant([1.2,7.3]) #----> float32

a.dtype , b.dtype

(tf.int32, tf.float32)

In [4]:
# change from float32 to float16
c = tf.cast(b,dtype=tf.float16)
c.dtype

tf.float16

In [5]:
#change from int32 to float32
d = tf.cast(a,dtype=tf.float16)
a, d

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>)

## Tensors Aggregation

### get aggregation of :
* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor

In [6]:
import numpy as np
aggregation_tensor = tf.constant(np.random.randint( 0,100, size=50))
aggregation_tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([78, 45, 33, 16, 41, 94, 34, 89, 87,  8,  2,  3, 46, 41, 82, 16, 70,
       45, 36, 21, 41, 43, 12, 50, 78, 95, 12, 73, 52, 54, 68, 30, 92, 20,
        0, 51, 56, 26, 78, 73, 83, 53, 39, 74, 13, 86, 60, 64, 62, 16])>

In [7]:
#Now to make aggregation
min_val = tf.reduce_min(aggregation_tensor)
max_val = tf.reduce_max(aggregation_tensor)
mean_val = tf.reduce_mean(aggregation_tensor)
sum_val = tf.reduce_sum(aggregation_tensor)

min_val , max_val , mean_val , sum_val

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=95>,
 <tf.Tensor: shape=(), dtype=int32, numpy=48>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2441>)

In [9]:
# variance
from tensorflow_probability import stats

ValueError: Arg specs do not match: original=FullArgSpec(args=['input', 'dtype', 'name', 'layout'], varargs=None, varkw=None, defaults=(None, None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), new=FullArgSpec(args=['input', 'dtype', 'name'], varargs=None, varkw=None, defaults=(None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), fn=<function ones_like_v2 at 0x000001CB853F5120>